// Opaque identifier helpers.
//
// - Internal primary keys are UUIDs (generated by Postgres gen_random_uuid()).
// - Public URL ids use a short, URL-safe, non-sequential NanoID so URLs can't
//   be enumerated (architecture plan §10).
// - The customer-facing tracking code is branded (NNPMLNNNNNNNN) but its
//   variable parts are random, so it's unguessable while still readable.

import { customAlphabet } from "nanoid";

// Unambiguous alphabet (no 0/O/1/I/l) for human-facing codes.
const URLSAFE = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
const DIGITS = "0123456789";

const publicIdGen = customAlphabet(URLSAFE, 12);
const trackingPrefixGen = customAlphabet(DIGITS, 2);
const trackingTailGen = customAlphabet(DIGITS, 8);

/** Opaque id for resource URLs, e.g. "8kQ2f7Zr9xAb". */
export function publicId(): string {
  return publicIdGen();
}

/**
 * Branded customer-facing tracking code: 2 random digits + "PML" + 8 random
 * digits, e.g. "41PML93820156". Random throughout so it's non-enumerable while
 * staying short and readable. 10^10 combinations make collisions negligible;
 * the tracking_code column is UNIQUE, so any collision would surface on insert.
 */
export function trackingCode(): string {
  return `${trackingPrefixGen()}PML${trackingTailGen()}`;
}

/** AWB number for print: numeric-ish, unique per order. */
const awbGen = customAlphabet("0123456789", 10);
export function awbNumber(): string {
  return awbGen();
}
