// Opaque identifier helpers.
//
// - Internal primary keys are UUIDs (generated by Postgres gen_random_uuid()).
// - Public URL ids use a short, URL-safe, non-sequential NanoID so URLs can't
//   be enumerated (architecture plan §10).
// - The customer-facing tracking code is branded (PML-YYYY-XXXXXXX) but its
//   variable part is random, so it's unguessable while still readable.

import { customAlphabet } from "nanoid";

// Unambiguous alphabet (no 0/O/1/I/l) for human-facing codes.
const READABLE = "23456789ABCDEFGHJKLMNPQRSTUVWXYZ";
const URLSAFE = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";

const publicIdGen = customAlphabet(URLSAFE, 12);
const trackingTailGen = customAlphabet(READABLE, 7);

/** Opaque id for resource URLs, e.g. "8kQ2f7Zr9xAb". */
export function publicId(): string {
  return publicIdGen();
}

/** Branded customer-facing tracking code, e.g. "PML-2026-8KQ2F7Z". */
export function trackingCode(now: Date = new Date()): string {
  return `PML-${now.getUTCFullYear()}-${trackingTailGen()}`;
}

/** AWB number for print: numeric-ish, unique per order. */
const awbGen = customAlphabet("0123456789", 10);
export function awbNumber(): string {
  return awbGen();
}
