import { chromium, type Browser } from "patchright";
import type { CarrierAdapter, NormalizedTracking, TrackingEvent, ShipmentStatus } from "./types.js";

// DHL's tracking data comes from https://www.dhl.com/utapi, which is
// protected by Akamai Bot Manager (ak_bmsc / bm_sz / _abck cookies).
// Those tokens are generated by JS that fingerprints a real browser, so
// we can't hit /utapi directly with fetch() - instead we drive a real
// (headless) browser to the actual tracking page and let its own request
// fire naturally, then intercept the response.
//
// Using patchright instead of vanilla playwright here - patchright patches
// the Chromium binary at build time (removing the Runtime.enable CDP leak
// and HeadlessChrome markers), which is the current best option for
// Node.js against Akamai/Cloudflare-class protection as of 2026. Vanilla
// playwright (even with playwright-extra + stealth plugin) is reliably
// detected by Akamai Bot Manager - that plugin hasn't been meaningfully
// updated since 2023.
//
// Why a real browser and not forged cookies: _abck/bm_sz are produced by
// Akamai's sensor JS fingerprinting the browser, then posted back to
// Akamai before the cookie is marked "validated". Copying captured cookie
// values into a plain fetch()/curl call works once, briefly, then gets
// flagged - bm_sz typically expires in ~30 min and is tied to the session
// that generated it. There's no way to generate a valid _abck from
// Node/Python alone without executing Akamai's real sensor JS.
//
// Cost tradeoff: this is much heavier than the other adapters (a few
// seconds and real browser memory per lookup vs. milliseconds for a
// plain HTTP call). Don't call this per customer page-load - run it on
// a schedule (background poller) and serve cached results to the portal.

const TRACKING_PAGE = "https://www.dhl.com/pk-en/home/tracking.html";

interface DhlEvent {
  timestamp: string; // has real timezone offset, e.g. "2026-07-02T12:33:00-04:00"
  location?: { address?: { addressLocality?: string; countryCode?: string } };
  statusCode: string;
  status: string;
  description: string;
}

interface DhlUtapiResponse {
  shipments: Array<{
    id: string;
    status: {
      timestamp: string;
      statusCode: string;
      description: string;
    };
    events: DhlEvent[];
  }>;
}

function mapStatus(statusCode: string, description: string): ShipmentStatus {
  const code = statusCode.toLowerCase();
  const desc = description.toLowerCase();
  if (code === "delivered" || desc.includes("delivered")) return "delivered";
  if (desc.includes("out with courier") || desc.includes("out for delivery")) return "out_for_delivery";
  if (code === "transit") return "in_transit";
  if (code === "unknown" && (desc.includes("payment") || desc.includes("received"))) return "info_received";
  if (code === "exception" || desc.includes("delay") || desc.includes("held")) return "exception";
  console.warn(`DHL: unmapped status code "${statusCode}" / "${description}"`);
  return "unknown";
}

// Reuse one browser instance across calls instead of launching a fresh
// one per lookup - launching Chromium is the expensive part.
let browserPromise: Promise<Browser> | null = null;
function getBrowser(): Promise<Browser> {
  if (!browserPromise) {
    // If Akamai challenges still show up in practice, the next lever to
    // try is headless: false running under Xvfb on the server (a virtual
    // display) - some Patchright users report headed mode holding up
    // better against Akamai specifically, at the cost of needing Xvfb
    // installed on your VPS.
    browserPromise = chromium.launch({ headless: true, channel: "chrome" });
  }
  return browserPromise;
}

export const dhlAdapter: CarrierAdapter = {
  carrierName: "dhl",

  async track(trackingNumber: string): Promise<NormalizedTracking | null> {
    const browser = await getBrowser();
    const context = await browser.newContext({
      userAgent:
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
      viewport: { width: 1280, height: 800 },
      locale: "en-US",
    });
    const page = await context.newPage();

    try {
      // Set up the response listener BEFORE navigating, so we don't
      // miss the /utapi call that fires automatically on page load
      // when tracking-id is in the query string.
      //
      // Akamai serves a proof-of-work challenge on the FIRST /utapi call:
      // it responds 428 with a `{"sec-cp-challenge":"true", ...}` body, the
      // page's JS solves it, then automatically retries and the SECOND
      // /utapi returns 200 with the real data. So we must wait for the
      // *successful* /utapi response, not merely the first one matching the
      // URL - otherwise we latch onto the 428 challenge and throw. A 404
      // (genuinely not found) is terminal, so we accept that too and handle
      // it below.
      const responsePromise = page.waitForResponse(
        (res) =>
          res.url().includes("/utapi") &&
          res.url().includes(trackingNumber) &&
          (res.ok() || res.status() === 404),
        { timeout: 30000 }
      );

      await page.goto(`${TRACKING_PAGE}?tracking-id=${encodeURIComponent(trackingNumber)}&submit=1`, {
        waitUntil: "domcontentloaded",
      });

      const response = await responsePromise;
      if (!response.ok()) {
        if (response.status() === 404) return null;
        throw new Error(`DHL: /utapi returned ${response.status()}`);
      }

      const json = (await response.json()) as DhlUtapiResponse;
      const shipment = json.shipments?.[0];
      if (!shipment) return null;

      const events: TrackingEvent[] = shipment.events.map((e) => ({
        timestamp: e.timestamp, // already ISO with real offset, no conversion needed
        location: e.location?.address?.addressLocality ?? null,
        description: e.description.trim(),
      }));
      // DHL returns newest-first already (matches our convention).

      return {
        carrier: "dhl",
        trackingNumber: shipment.id,
        status: mapStatus(shipment.status.statusCode, shipment.status.description),
        statusText: shipment.status.description,
        estimatedDelivery: null, // not present in this response shape - check other statuses/shipment types for a delivery-date field
        events,
        raw: json,
        fetchedAt: new Date().toISOString(),
      };
    } catch (err) {
      if (err instanceof Error && err.message.includes("Timeout")) {
        // Could mean: not found, OR Akamai served a challenge page instead
        // of the real tracking flow. Worth distinguishing in production -
        // check page content for a captcha/challenge indicator here if
        // this fires often.
        return null;
      }
      throw err;
    } finally {
      await context.close();
    }
  },
};

// Call this on process shutdown to clean up the shared browser instance.
export async function closeDhlBrowser(): Promise<void> {
  if (browserPromise) {
    const browser = await browserPromise;
    await browser.close();
    browserPromise = null;
  }
}
